default_lang: "ru"
models_dir: "D:\\Models\\lmstudio-community"
llama_exe_path: "D:\\Programs\\llama.cpp\\llama.exe"
flags:
  "--ctx-size": {"value": "262144", "active": true, "type": "entry", "desc": "desc_ctx"}
  "--gpu-layers": {"value": "600", "active": true, "type": "entry", "desc": "desc_gpu"}
  "--batch-size": {"value": "512", "active": true, "type": "entry", "desc": "desc_batch"}
  "--ubatch-size": {"value": "256", "active": true, "type": "entry", "desc": "desc_ubatch"}
  "--flash-attn": {"value": "on", "active": true, "type": "combo", "options": ["on", "off", "auto"], "desc": "desc_flash"}
  "--temp": {"value": "0.6", "active": true, "type": "entry", "desc": "desc_temp"}
  "--top-k": {"value": "20", "active": true, "type": "entry", "desc": "desc_topk"}
  "--top-p": {"value": "0.95", "active": true, "type": "entry", "desc": "desc_topp"}
  "--repeat-penalty": {"value": "1.0", "active": true, "type": "entry", "desc": "desc_repeat"}
  "--presence-penalty": {"value": "0.0", "active": true, "type": "entry", "desc": "desc_presence"}
  "--spec-type": {"value": "draft-mtp", "active": false, "type": "combo", "options": ["draft-simple", "draft-eagle3", "draft-dflash", "draft-dspark", "draft-mtp", "ngram-cache", "ngram-simple", "ngram-map-k", "ngram-map-k4v", "ngram-mod"], "desc": "desc_spectype"}
  "--spec-draft-n-max": {"value": "2", "active": false, "type": "entry", "desc": "desc_specmax"}
  "--alias": {"value": "", "active": true, "type": "entry", "desc": "desc_alias"}
  "--n-cpu-moe": {"value": "46", "active": false, "type": "entry", "desc": "desc_n_cpu_moe"}
  "--port": {"value": "3090", "active": true, "type": "entry", "desc": "desc_port"}
  "--min-p": {"value": "0.05", "active": true, "type": "entry", "desc": "desc_minp"}
  "--cache-type-k": {"value": "q8_0", "active": false, "type": "combo", "options": ["q4_0", "q4_1", "q5_0", "q5_1", "q8_0", "f16", "f32"], "desc": "desc_cache_type_k"}
  "--cache-type-v": {"value": "q8_0", "active": false, "type": "combo", "options": ["q4_0", "q4_1", "q5_0", "q5_1", "q8_0", "f16", "f32"], "desc": "desc_cache_type_v"}
  "--jinja": {"active": false, "type": "checkbox", "desc": "desc_jinja"}
  "--cont-batching": {"active": false, "type": "checkbox", "desc": "desc_cont_batching"}
  "--tensor-split": {"value": "4,1", "active": false, "type": "combo", "options": ["1,1", "2,1", "4,1", "8,1", "16,1"], "desc": "desc_tensor"}
  "--split-mode": {"value": "layer", "active": false, "type": "combo", "options": ["none", "layer", "row"], "desc": "desc_split_mode"}
  "--main-gpu": {"value": "0", "active": false, "type": "entry", "desc": "desc_main_gpu"}
  "--parallel": {"value": "1", "active": false, "type": "entry", "desc": "desc_parallel"}
  "--fit": {"value": "on", "active": false, "type": "combo", "options": ["on", "off"], "desc": "desc_fit"}
  "--fit-target": {"value": "1024", "active": false, "type": "entry", "desc": "desc_fit_target"}